#pragma once

#include "CoreMinimal.h"
#include "MavLink.h"
#include "MavLinkDispatch.generated.h"

 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_heartbeat, FMavlinkMsg_heartbeat );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_sys_status, FMavlinkMsg_sys_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_system_time, FMavlinkMsg_system_time );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_ping, FMavlinkMsg_ping );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_change_operator_control, FMavlinkMsg_change_operator_control );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_change_operator_control_ack, FMavlinkMsg_change_operator_control_ack );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_auth_key, FMavlinkMsg_auth_key );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_set_mode, FMavlinkMsg_set_mode );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_param_request_read, FMavlinkMsg_param_request_read );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_param_request_list, FMavlinkMsg_param_request_list );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_param_value, FMavlinkMsg_param_value );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_param_set, FMavlinkMsg_param_set );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_gps_raw_int, FMavlinkMsg_gps_raw_int );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_gps_status, FMavlinkMsg_gps_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_scaled_imu, FMavlinkMsg_scaled_imu );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_raw_imu, FMavlinkMsg_raw_imu );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_raw_pressure, FMavlinkMsg_raw_pressure );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_scaled_pressure, FMavlinkMsg_scaled_pressure );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_attitude, FMavlinkMsg_attitude );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_attitude_quaternion, FMavlinkMsg_attitude_quaternion );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_local_position_ned, FMavlinkMsg_local_position_ned );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_global_position_int, FMavlinkMsg_global_position_int );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_rc_channels_scaled, FMavlinkMsg_rc_channels_scaled );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_rc_channels_raw, FMavlinkMsg_rc_channels_raw );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_servo_output_raw, FMavlinkMsg_servo_output_raw );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_request_partial_list, FMavlinkMsg_mission_request_partial_list );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_write_partial_list, FMavlinkMsg_mission_write_partial_list );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_item, FMavlinkMsg_mission_item );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_request, FMavlinkMsg_mission_request );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_set_current, FMavlinkMsg_mission_set_current );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_current, FMavlinkMsg_mission_current );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_request_list, FMavlinkMsg_mission_request_list );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_count, FMavlinkMsg_mission_count );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_clear_all, FMavlinkMsg_mission_clear_all );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_item_reached, FMavlinkMsg_mission_item_reached );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_ack, FMavlinkMsg_mission_ack );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_set_gps_global_origin, FMavlinkMsg_set_gps_global_origin );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_gps_global_origin, FMavlinkMsg_gps_global_origin );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_param_map_rc, FMavlinkMsg_param_map_rc );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_request_int, FMavlinkMsg_mission_request_int );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_safety_set_allowed_area, FMavlinkMsg_safety_set_allowed_area );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_safety_allowed_area, FMavlinkMsg_safety_allowed_area );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_attitude_quaternion_cov, FMavlinkMsg_attitude_quaternion_cov );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_nav_controller_output, FMavlinkMsg_nav_controller_output );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_global_position_int_cov, FMavlinkMsg_global_position_int_cov );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_local_position_ned_cov, FMavlinkMsg_local_position_ned_cov );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_rc_channels, FMavlinkMsg_rc_channels );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_request_data_stream, FMavlinkMsg_request_data_stream );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_data_stream, FMavlinkMsg_data_stream );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_manual_control, FMavlinkMsg_manual_control );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_rc_channels_override, FMavlinkMsg_rc_channels_override );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mission_item_int, FMavlinkMsg_mission_item_int );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_vfr_hud, FMavlinkMsg_vfr_hud );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_command_int, FMavlinkMsg_command_int );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_command_long, FMavlinkMsg_command_long );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_command_ack, FMavlinkMsg_command_ack );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_manual_setpoint, FMavlinkMsg_manual_setpoint );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_set_attitude_target, FMavlinkMsg_set_attitude_target );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_attitude_target, FMavlinkMsg_attitude_target );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_set_position_target_local_ned, FMavlinkMsg_set_position_target_local_ned );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_position_target_local_ned, FMavlinkMsg_position_target_local_ned );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_set_position_target_global_int, FMavlinkMsg_set_position_target_global_int );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_position_target_global_int, FMavlinkMsg_position_target_global_int );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_local_position_ned_system_global_offset, FMavlinkMsg_local_position_ned_system_global_offset );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_hil_state, FMavlinkMsg_hil_state );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_hil_controls, FMavlinkMsg_hil_controls );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_hil_rc_inputs_raw, FMavlinkMsg_hil_rc_inputs_raw );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_hil_actuator_controls, FMavlinkMsg_hil_actuator_controls );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_optical_flow, FMavlinkMsg_optical_flow );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_global_vision_position_estimate, FMavlinkMsg_global_vision_position_estimate );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_vision_position_estimate, FMavlinkMsg_vision_position_estimate );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_vision_speed_estimate, FMavlinkMsg_vision_speed_estimate );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_vicon_position_estimate, FMavlinkMsg_vicon_position_estimate );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_highres_imu, FMavlinkMsg_highres_imu );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_optical_flow_rad, FMavlinkMsg_optical_flow_rad );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_hil_sensor, FMavlinkMsg_hil_sensor );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_sim_state, FMavlinkMsg_sim_state );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_radio_status, FMavlinkMsg_radio_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_file_transfer_protocol, FMavlinkMsg_file_transfer_protocol );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_timesync, FMavlinkMsg_timesync );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_camera_trigger, FMavlinkMsg_camera_trigger );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_hil_gps, FMavlinkMsg_hil_gps );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_hil_optical_flow, FMavlinkMsg_hil_optical_flow );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_hil_state_quaternion, FMavlinkMsg_hil_state_quaternion );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_scaled_imu2, FMavlinkMsg_scaled_imu2 );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_log_request_list, FMavlinkMsg_log_request_list );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_log_entry, FMavlinkMsg_log_entry );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_log_request_data, FMavlinkMsg_log_request_data );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_log_data, FMavlinkMsg_log_data );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_log_erase, FMavlinkMsg_log_erase );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_log_request_end, FMavlinkMsg_log_request_end );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_gps_inject_data, FMavlinkMsg_gps_inject_data );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_gps2_raw, FMavlinkMsg_gps2_raw );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_power_status, FMavlinkMsg_power_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_serial_control, FMavlinkMsg_serial_control );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_gps_rtk, FMavlinkMsg_gps_rtk );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_gps2_rtk, FMavlinkMsg_gps2_rtk );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_scaled_imu3, FMavlinkMsg_scaled_imu3 );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_data_transmission_handshake, FMavlinkMsg_data_transmission_handshake );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_encapsulated_data, FMavlinkMsg_encapsulated_data );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_distance_sensor, FMavlinkMsg_distance_sensor );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_terrain_request, FMavlinkMsg_terrain_request );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_terrain_data, FMavlinkMsg_terrain_data );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_terrain_check, FMavlinkMsg_terrain_check );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_terrain_report, FMavlinkMsg_terrain_report );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_scaled_pressure2, FMavlinkMsg_scaled_pressure2 );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_att_pos_mocap, FMavlinkMsg_att_pos_mocap );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_set_actuator_control_target, FMavlinkMsg_set_actuator_control_target );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_actuator_control_target, FMavlinkMsg_actuator_control_target );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_altitude, FMavlinkMsg_altitude );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_resource_request, FMavlinkMsg_resource_request );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_scaled_pressure3, FMavlinkMsg_scaled_pressure3 );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_follow_target, FMavlinkMsg_follow_target );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_control_system_state, FMavlinkMsg_control_system_state );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_battery_status, FMavlinkMsg_battery_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_autopilot_version, FMavlinkMsg_autopilot_version );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_landing_target, FMavlinkMsg_landing_target );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_estimator_status, FMavlinkMsg_estimator_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_wind_cov, FMavlinkMsg_wind_cov );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_gps_input, FMavlinkMsg_gps_input );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_gps_rtcm_data, FMavlinkMsg_gps_rtcm_data );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_high_latency, FMavlinkMsg_high_latency );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_high_latency2, FMavlinkMsg_high_latency2 );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_vibration, FMavlinkMsg_vibration );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_home_position, FMavlinkMsg_home_position );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_set_home_position, FMavlinkMsg_set_home_position );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_message_interval, FMavlinkMsg_message_interval );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_extended_sys_state, FMavlinkMsg_extended_sys_state );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_adsb_vehicle, FMavlinkMsg_adsb_vehicle );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_collision, FMavlinkMsg_collision );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_v2_extension, FMavlinkMsg_v2_extension );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_memory_vect, FMavlinkMsg_memory_vect );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_debug_vect, FMavlinkMsg_debug_vect );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_named_value_float, FMavlinkMsg_named_value_float );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_named_value_int, FMavlinkMsg_named_value_int );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_statustext, FMavlinkMsg_statustext );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_debug, FMavlinkMsg_debug );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_setup_signing, FMavlinkMsg_setup_signing );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_button_change, FMavlinkMsg_button_change );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_play_tune, FMavlinkMsg_play_tune );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_camera_information, FMavlinkMsg_camera_information );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_camera_settings, FMavlinkMsg_camera_settings );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_storage_information, FMavlinkMsg_storage_information );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_camera_capture_status, FMavlinkMsg_camera_capture_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_camera_image_captured, FMavlinkMsg_camera_image_captured );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_flight_information, FMavlinkMsg_flight_information );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_mount_orientation, FMavlinkMsg_mount_orientation );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_logging_data, FMavlinkMsg_logging_data );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_logging_data_acked, FMavlinkMsg_logging_data_acked );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_logging_ack, FMavlinkMsg_logging_ack );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_video_stream_information, FMavlinkMsg_video_stream_information );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_video_stream_status, FMavlinkMsg_video_stream_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_wifi_config_ap, FMavlinkMsg_wifi_config_ap );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_protocol_version, FMavlinkMsg_protocol_version );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_uavcan_node_status, FMavlinkMsg_uavcan_node_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_uavcan_node_info, FMavlinkMsg_uavcan_node_info );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_param_ext_request_read, FMavlinkMsg_param_ext_request_read );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_param_ext_request_list, FMavlinkMsg_param_ext_request_list );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_param_ext_value, FMavlinkMsg_param_ext_value );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_param_ext_set, FMavlinkMsg_param_ext_set );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_param_ext_ack, FMavlinkMsg_param_ext_ack );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_obstacle_distance, FMavlinkMsg_obstacle_distance );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_odometry, FMavlinkMsg_odometry );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_trajectory_representation_waypoints, FMavlinkMsg_trajectory_representation_waypoints );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_trajectory_representation_bezier, FMavlinkMsg_trajectory_representation_bezier );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_cellular_status, FMavlinkMsg_cellular_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_utm_global_position, FMavlinkMsg_utm_global_position );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_debug_float_array, FMavlinkMsg_debug_float_array );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_orbit_execution_status, FMavlinkMsg_orbit_execution_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_statustext_long, FMavlinkMsg_statustext_long );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_smart_battery_info, FMavlinkMsg_smart_battery_info );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_smart_battery_status, FMavlinkMsg_smart_battery_status );
 DECLARE_DELEGATE_OneParam( FOnMsgDelegate_wheel_distance, FMavlinkMsg_wheel_distance );

struct __mavlink_message;

USTRUCT(BlueprintType)
struct FMavlinkDispatch
{
    GENERATED_BODY()

    FOnMsgDelegate_heartbeat FOnMavlinkMsg_heartbeat;
    FOnMsgDelegate_sys_status FOnMavlinkMsg_sys_status;
    FOnMsgDelegate_system_time FOnMavlinkMsg_system_time;
    FOnMsgDelegate_ping FOnMavlinkMsg_ping;
    FOnMsgDelegate_change_operator_control FOnMavlinkMsg_change_operator_control;
    FOnMsgDelegate_change_operator_control_ack FOnMavlinkMsg_change_operator_control_ack;
    FOnMsgDelegate_auth_key FOnMavlinkMsg_auth_key;
    FOnMsgDelegate_set_mode FOnMavlinkMsg_set_mode;
    FOnMsgDelegate_param_request_read FOnMavlinkMsg_param_request_read;
    FOnMsgDelegate_param_request_list FOnMavlinkMsg_param_request_list;
    FOnMsgDelegate_param_value FOnMavlinkMsg_param_value;
    FOnMsgDelegate_param_set FOnMavlinkMsg_param_set;
    FOnMsgDelegate_gps_raw_int FOnMavlinkMsg_gps_raw_int;
    FOnMsgDelegate_gps_status FOnMavlinkMsg_gps_status;
    FOnMsgDelegate_scaled_imu FOnMavlinkMsg_scaled_imu;
    FOnMsgDelegate_raw_imu FOnMavlinkMsg_raw_imu;
    FOnMsgDelegate_raw_pressure FOnMavlinkMsg_raw_pressure;
    FOnMsgDelegate_scaled_pressure FOnMavlinkMsg_scaled_pressure;
    FOnMsgDelegate_attitude FOnMavlinkMsg_attitude;
    FOnMsgDelegate_attitude_quaternion FOnMavlinkMsg_attitude_quaternion;
    FOnMsgDelegate_local_position_ned FOnMavlinkMsg_local_position_ned;
    FOnMsgDelegate_global_position_int FOnMavlinkMsg_global_position_int;
    FOnMsgDelegate_rc_channels_scaled FOnMavlinkMsg_rc_channels_scaled;
    FOnMsgDelegate_rc_channels_raw FOnMavlinkMsg_rc_channels_raw;
    FOnMsgDelegate_servo_output_raw FOnMavlinkMsg_servo_output_raw;
    FOnMsgDelegate_mission_request_partial_list FOnMavlinkMsg_mission_request_partial_list;
    FOnMsgDelegate_mission_write_partial_list FOnMavlinkMsg_mission_write_partial_list;
    FOnMsgDelegate_mission_item FOnMavlinkMsg_mission_item;
    FOnMsgDelegate_mission_request FOnMavlinkMsg_mission_request;
    FOnMsgDelegate_mission_set_current FOnMavlinkMsg_mission_set_current;
    FOnMsgDelegate_mission_current FOnMavlinkMsg_mission_current;
    FOnMsgDelegate_mission_request_list FOnMavlinkMsg_mission_request_list;
    FOnMsgDelegate_mission_count FOnMavlinkMsg_mission_count;
    FOnMsgDelegate_mission_clear_all FOnMavlinkMsg_mission_clear_all;
    FOnMsgDelegate_mission_item_reached FOnMavlinkMsg_mission_item_reached;
    FOnMsgDelegate_mission_ack FOnMavlinkMsg_mission_ack;
    FOnMsgDelegate_set_gps_global_origin FOnMavlinkMsg_set_gps_global_origin;
    FOnMsgDelegate_gps_global_origin FOnMavlinkMsg_gps_global_origin;
    FOnMsgDelegate_param_map_rc FOnMavlinkMsg_param_map_rc;
    FOnMsgDelegate_mission_request_int FOnMavlinkMsg_mission_request_int;
    FOnMsgDelegate_safety_set_allowed_area FOnMavlinkMsg_safety_set_allowed_area;
    FOnMsgDelegate_safety_allowed_area FOnMavlinkMsg_safety_allowed_area;
    FOnMsgDelegate_attitude_quaternion_cov FOnMavlinkMsg_attitude_quaternion_cov;
    FOnMsgDelegate_nav_controller_output FOnMavlinkMsg_nav_controller_output;
    FOnMsgDelegate_global_position_int_cov FOnMavlinkMsg_global_position_int_cov;
    FOnMsgDelegate_local_position_ned_cov FOnMavlinkMsg_local_position_ned_cov;
    FOnMsgDelegate_rc_channels FOnMavlinkMsg_rc_channels;
    FOnMsgDelegate_request_data_stream FOnMavlinkMsg_request_data_stream;
    FOnMsgDelegate_data_stream FOnMavlinkMsg_data_stream;
    FOnMsgDelegate_manual_control FOnMavlinkMsg_manual_control;
    FOnMsgDelegate_rc_channels_override FOnMavlinkMsg_rc_channels_override;
    FOnMsgDelegate_mission_item_int FOnMavlinkMsg_mission_item_int;
    FOnMsgDelegate_vfr_hud FOnMavlinkMsg_vfr_hud;
    FOnMsgDelegate_command_int FOnMavlinkMsg_command_int;
    FOnMsgDelegate_command_long FOnMavlinkMsg_command_long;
    FOnMsgDelegate_command_ack FOnMavlinkMsg_command_ack;
    FOnMsgDelegate_manual_setpoint FOnMavlinkMsg_manual_setpoint;
    FOnMsgDelegate_set_attitude_target FOnMavlinkMsg_set_attitude_target;
    FOnMsgDelegate_attitude_target FOnMavlinkMsg_attitude_target;
    FOnMsgDelegate_set_position_target_local_ned FOnMavlinkMsg_set_position_target_local_ned;
    FOnMsgDelegate_position_target_local_ned FOnMavlinkMsg_position_target_local_ned;
    FOnMsgDelegate_set_position_target_global_int FOnMavlinkMsg_set_position_target_global_int;
    FOnMsgDelegate_position_target_global_int FOnMavlinkMsg_position_target_global_int;
    FOnMsgDelegate_local_position_ned_system_global_offset FOnMavlinkMsg_local_position_ned_system_global_offset;
    FOnMsgDelegate_hil_state FOnMavlinkMsg_hil_state;
    FOnMsgDelegate_hil_controls FOnMavlinkMsg_hil_controls;
    FOnMsgDelegate_hil_rc_inputs_raw FOnMavlinkMsg_hil_rc_inputs_raw;
    FOnMsgDelegate_hil_actuator_controls FOnMavlinkMsg_hil_actuator_controls;
    FOnMsgDelegate_optical_flow FOnMavlinkMsg_optical_flow;
    FOnMsgDelegate_global_vision_position_estimate FOnMavlinkMsg_global_vision_position_estimate;
    FOnMsgDelegate_vision_position_estimate FOnMavlinkMsg_vision_position_estimate;
    FOnMsgDelegate_vision_speed_estimate FOnMavlinkMsg_vision_speed_estimate;
    FOnMsgDelegate_vicon_position_estimate FOnMavlinkMsg_vicon_position_estimate;
    FOnMsgDelegate_highres_imu FOnMavlinkMsg_highres_imu;
    FOnMsgDelegate_optical_flow_rad FOnMavlinkMsg_optical_flow_rad;
    FOnMsgDelegate_hil_sensor FOnMavlinkMsg_hil_sensor;
    FOnMsgDelegate_sim_state FOnMavlinkMsg_sim_state;
    FOnMsgDelegate_radio_status FOnMavlinkMsg_radio_status;
    FOnMsgDelegate_file_transfer_protocol FOnMavlinkMsg_file_transfer_protocol;
    FOnMsgDelegate_timesync FOnMavlinkMsg_timesync;
    FOnMsgDelegate_camera_trigger FOnMavlinkMsg_camera_trigger;
    FOnMsgDelegate_hil_gps FOnMavlinkMsg_hil_gps;
    FOnMsgDelegate_hil_optical_flow FOnMavlinkMsg_hil_optical_flow;
    FOnMsgDelegate_hil_state_quaternion FOnMavlinkMsg_hil_state_quaternion;
    FOnMsgDelegate_scaled_imu2 FOnMavlinkMsg_scaled_imu2;
    FOnMsgDelegate_log_request_list FOnMavlinkMsg_log_request_list;
    FOnMsgDelegate_log_entry FOnMavlinkMsg_log_entry;
    FOnMsgDelegate_log_request_data FOnMavlinkMsg_log_request_data;
    FOnMsgDelegate_log_data FOnMavlinkMsg_log_data;
    FOnMsgDelegate_log_erase FOnMavlinkMsg_log_erase;
    FOnMsgDelegate_log_request_end FOnMavlinkMsg_log_request_end;
    FOnMsgDelegate_gps_inject_data FOnMavlinkMsg_gps_inject_data;
    FOnMsgDelegate_gps2_raw FOnMavlinkMsg_gps2_raw;
    FOnMsgDelegate_power_status FOnMavlinkMsg_power_status;
    FOnMsgDelegate_serial_control FOnMavlinkMsg_serial_control;
    FOnMsgDelegate_gps_rtk FOnMavlinkMsg_gps_rtk;
    FOnMsgDelegate_gps2_rtk FOnMavlinkMsg_gps2_rtk;
    FOnMsgDelegate_scaled_imu3 FOnMavlinkMsg_scaled_imu3;
    FOnMsgDelegate_data_transmission_handshake FOnMavlinkMsg_data_transmission_handshake;
    FOnMsgDelegate_encapsulated_data FOnMavlinkMsg_encapsulated_data;
    FOnMsgDelegate_distance_sensor FOnMavlinkMsg_distance_sensor;
    FOnMsgDelegate_terrain_request FOnMavlinkMsg_terrain_request;
    FOnMsgDelegate_terrain_data FOnMavlinkMsg_terrain_data;
    FOnMsgDelegate_terrain_check FOnMavlinkMsg_terrain_check;
    FOnMsgDelegate_terrain_report FOnMavlinkMsg_terrain_report;
    FOnMsgDelegate_scaled_pressure2 FOnMavlinkMsg_scaled_pressure2;
    FOnMsgDelegate_att_pos_mocap FOnMavlinkMsg_att_pos_mocap;
    FOnMsgDelegate_set_actuator_control_target FOnMavlinkMsg_set_actuator_control_target;
    FOnMsgDelegate_actuator_control_target FOnMavlinkMsg_actuator_control_target;
    FOnMsgDelegate_altitude FOnMavlinkMsg_altitude;
    FOnMsgDelegate_resource_request FOnMavlinkMsg_resource_request;
    FOnMsgDelegate_scaled_pressure3 FOnMavlinkMsg_scaled_pressure3;
    FOnMsgDelegate_follow_target FOnMavlinkMsg_follow_target;
    FOnMsgDelegate_control_system_state FOnMavlinkMsg_control_system_state;
    FOnMsgDelegate_battery_status FOnMavlinkMsg_battery_status;
    FOnMsgDelegate_autopilot_version FOnMavlinkMsg_autopilot_version;
    FOnMsgDelegate_landing_target FOnMavlinkMsg_landing_target;
    FOnMsgDelegate_estimator_status FOnMavlinkMsg_estimator_status;
    FOnMsgDelegate_wind_cov FOnMavlinkMsg_wind_cov;
    FOnMsgDelegate_gps_input FOnMavlinkMsg_gps_input;
    FOnMsgDelegate_gps_rtcm_data FOnMavlinkMsg_gps_rtcm_data;
    FOnMsgDelegate_high_latency FOnMavlinkMsg_high_latency;
    FOnMsgDelegate_high_latency2 FOnMavlinkMsg_high_latency2;
    FOnMsgDelegate_vibration FOnMavlinkMsg_vibration;
    FOnMsgDelegate_home_position FOnMavlinkMsg_home_position;
    FOnMsgDelegate_set_home_position FOnMavlinkMsg_set_home_position;
    FOnMsgDelegate_message_interval FOnMavlinkMsg_message_interval;
    FOnMsgDelegate_extended_sys_state FOnMavlinkMsg_extended_sys_state;
    FOnMsgDelegate_adsb_vehicle FOnMavlinkMsg_adsb_vehicle;
    FOnMsgDelegate_collision FOnMavlinkMsg_collision;
    FOnMsgDelegate_v2_extension FOnMavlinkMsg_v2_extension;
    FOnMsgDelegate_memory_vect FOnMavlinkMsg_memory_vect;
    FOnMsgDelegate_debug_vect FOnMavlinkMsg_debug_vect;
    FOnMsgDelegate_named_value_float FOnMavlinkMsg_named_value_float;
    FOnMsgDelegate_named_value_int FOnMavlinkMsg_named_value_int;
    FOnMsgDelegate_statustext FOnMavlinkMsg_statustext;
    FOnMsgDelegate_debug FOnMavlinkMsg_debug;
    FOnMsgDelegate_setup_signing FOnMavlinkMsg_setup_signing;
    FOnMsgDelegate_button_change FOnMavlinkMsg_button_change;
    FOnMsgDelegate_play_tune FOnMavlinkMsg_play_tune;
    FOnMsgDelegate_camera_information FOnMavlinkMsg_camera_information;
    FOnMsgDelegate_camera_settings FOnMavlinkMsg_camera_settings;
    FOnMsgDelegate_storage_information FOnMavlinkMsg_storage_information;
    FOnMsgDelegate_camera_capture_status FOnMavlinkMsg_camera_capture_status;
    FOnMsgDelegate_camera_image_captured FOnMavlinkMsg_camera_image_captured;
    FOnMsgDelegate_flight_information FOnMavlinkMsg_flight_information;
    FOnMsgDelegate_mount_orientation FOnMavlinkMsg_mount_orientation;
    FOnMsgDelegate_logging_data FOnMavlinkMsg_logging_data;
    FOnMsgDelegate_logging_data_acked FOnMavlinkMsg_logging_data_acked;
    FOnMsgDelegate_logging_ack FOnMavlinkMsg_logging_ack;
    FOnMsgDelegate_video_stream_information FOnMavlinkMsg_video_stream_information;
    FOnMsgDelegate_video_stream_status FOnMavlinkMsg_video_stream_status;
    FOnMsgDelegate_wifi_config_ap FOnMavlinkMsg_wifi_config_ap;
    FOnMsgDelegate_protocol_version FOnMavlinkMsg_protocol_version;
    FOnMsgDelegate_uavcan_node_status FOnMavlinkMsg_uavcan_node_status;
    FOnMsgDelegate_uavcan_node_info FOnMavlinkMsg_uavcan_node_info;
    FOnMsgDelegate_param_ext_request_read FOnMavlinkMsg_param_ext_request_read;
    FOnMsgDelegate_param_ext_request_list FOnMavlinkMsg_param_ext_request_list;
    FOnMsgDelegate_param_ext_value FOnMavlinkMsg_param_ext_value;
    FOnMsgDelegate_param_ext_set FOnMavlinkMsg_param_ext_set;
    FOnMsgDelegate_param_ext_ack FOnMavlinkMsg_param_ext_ack;
    FOnMsgDelegate_obstacle_distance FOnMavlinkMsg_obstacle_distance;
    FOnMsgDelegate_odometry FOnMavlinkMsg_odometry;
    FOnMsgDelegate_trajectory_representation_waypoints FOnMavlinkMsg_trajectory_representation_waypoints;
    FOnMsgDelegate_trajectory_representation_bezier FOnMavlinkMsg_trajectory_representation_bezier;
    FOnMsgDelegate_cellular_status FOnMavlinkMsg_cellular_status;
    FOnMsgDelegate_utm_global_position FOnMavlinkMsg_utm_global_position;
    FOnMsgDelegate_debug_float_array FOnMavlinkMsg_debug_float_array;
    FOnMsgDelegate_orbit_execution_status FOnMavlinkMsg_orbit_execution_status;
    FOnMsgDelegate_statustext_long FOnMavlinkMsg_statustext_long;
    FOnMsgDelegate_smart_battery_info FOnMavlinkMsg_smart_battery_info;
    FOnMsgDelegate_smart_battery_status FOnMavlinkMsg_smart_battery_status;
    FOnMsgDelegate_wheel_distance FOnMavlinkMsg_wheel_distance;
    

    void DispatchMessage(const __mavlink_message& msg);
};
